### ISSUE TITLE
Working behind ntlm

### ISSUE THREAD

**Issue by josephwinston** [errordeveloper/weave-demos#5]
I work behind a ntlm proxy and know the tricks needed to get Vagrant, coreos, and docker to work behind ntlm.  Would it be worthwhile for a pull request that would allow ntlm support?

**Comment by errordeveloper** [comment]
@josephwinston I apologies for missing this! Any changed to CoreOS-based Vargantfile would have to be made against [coreos/coreos-vagrant](https://github.com/coreos/coreos-vagrant/) and I would then do a sub-tree pull here.
