### ISSUE TITLE
upgrade quartet to weave 1.0.1

### ISSUE THREAD

**Issue by tobowers** [errordeveloper/weave-demos#6]
Hello! It took a bunch of changes for me to get weave 1.0.1 to work on swarm 0.3 and machine 0.2. (In fact, it didn't even actually work with 0.11.0).

Here's where I left off: https://github.com/errordeveloper/weave-demos/compare/master...tobowers:feature/upgrade-weave-1.0.1

That's, obviously, not really ready to be a PR because of the hard coded paths. The docker-machine creation defaults to using TLS (maybe that changed?) and so a lot of the code needs to reflect that.

**Comment by errordeveloper** [comment]
The origin quartet demo is now moved to another repo and [document in great detail on our website](http://weave.works/guides/weave-and-docker-platform/index.html).
