### ISSUE TITLE
dependency failed

### ISSUE THREAD

**Issue by richardxy** [errordeveloper/weave-demos#7]
I was very excited to try it but got some issues that prevented it from working. 

When I ran "vagrant ssh core-01", it showed:
CoreOS alpha (752.1.0)
Update Strategy: No Reboots
Failed Units: 3
  pull-elasticsearch-image.service
  pull-spark-image.service
  weave.service

Then when I ran "journalctl -f -u spark",  it showed:
-- Logs begin at Mon 2015-07-27 16:17:00 UTC. --
Jul 27 16:17:36 core-02 systemd[1]: Dependency failed for Apache Spark Cluster.
Jul 27 16:17:36 core-02 systemd[1]: spark.service: Job spark.service/start failed with result 'dependency'.

Fixes will be greatly appreciated.

Richard

**Comment by richardxy** [comment]
I'm running Ubuntu 14.04. Thanks.

**Comment by errordeveloper** [comment]
Could you please show the output of `systemctl status weave`?
